package constants

const (
	Label1Text      = "Command/Flag"
	Label2Text      = "Alias"
	Label27Text     = "Default Value"
	Label3Text      = "Short Help Text"
	Label4Text      = "Long Help Text"
	Label5Text      = "List Child Commands/Flags"
	Label6Text      = "Parent Command/Flag"
	Label7Text      = "Code to Execute"
	Button1Text     = "Store/Next Command"
	Button1TextFlag = "Store/Next Flag"
	Button2Text     = "Previous Command"
	Button2TextFlag = "Previous Flag"
	Button3Text     = "Clear Command"
	Button3TextFlag = "Clear Flag"
	Button4Text     = "Delete Command"
	Button4TextFlag = "Delete Flag"
	Button5Text     = "Save"

	Info1Text        = "Options "
	Info2Text        = "Command Parameter(s)"
	Info3Text        = "Command Parameter Type"
	CheckText1       = "Default Command"
	CheckText2       = "Exclusive Command"
	CheckText3       = "Required Command"
	NELabelText      = "Fixed Number"
	Select1Text1     = "None"
	OptCheckText     = "Parameter(s) Optional"
	Select1Text3     = "Fixed Number"
	Select1Text4     = "Variable Number"
	Select2LabelText = "Select Parameter Type"
	Select2Bool      = "Bool"
	Select2Str       = "String"
	Select2Int       = "Integer"
	Select2Float     = "Float"
	Select2Time      = "Time"
	Select2Duration  = "Time Duration"
	Select2Date      = "Date"
	Select2Path      = "File Path"
	Select2URL       = "URL"
	Select2IP        = "IP Address"
	Select2Email     = "Email Address"
	Select2Phone     = "Phone Number"
)
const (
	AssetsPath = "/home/westarver/go/src/boa-constructor-work/boa-constructor-cmd/assets/"
)

// content generated by constantly
// from input by Jimmy for app Boa-Constructor

type ArgType int

// methods on the type

// String returns the constant's name as a string
// satisfies the Stringer interface
func (c ArgType) String() string {
	return _ArgTypeConstString(c)
}

const (
	ArgFlag ArgType = iota
	ArgCommand
	ArgInvalid = -1
)

// _ArgTypeConstString is a utlity function called internally
// is not exported
func _ArgTypeConstString(c ArgType) string {
	switch c {
	case ArgFlag:
		return "ArgFlag"
	case ArgCommand:
		return "ArgCommand"
	case ArgInvalid:
		return "ArgInvalid"
	}
	return ""
}

// end of content generated by constantly
